from pathlib import Path

from agents import Agent, Runner


BASE_DIR = Path(__file__).parent.parent
SITES_DIR = BASE_DIR / "sites"

class EmailWriter:
    def __init__(self, site: str, history=None):
        """
        Initialize EmailWriter with site content
        
        Args:
            site: The site identifier
        """
        content_file = SITES_DIR / site / "content.md"
        if content_file.exists():
            with open(content_file, "r", encoding="utf-8") as f:
                content = f.read()
        else:
            raise ValueError(f"Content file not found for site '{site}'")
        self.content = content

        self.agent = Agent(
            name="Assistant", 
            instructions=f"""\
You are a helpful assistant that is going to write an email based on the content given from content.md {site}. The website content is:

{self.content}""")

    async def write(self, message):
        """
        Write an email using the site content.
        
        Args:
            message: The current site and its content
        
        Returns:
            The email text generated by the agent in new file sites/{site}/email.txt
        """