"""
HTML Generator - Converts markdown back to HTML
"""

import markdown
from pathlib import Path
from utils.logger import setup_logger

logger = setup_logger(__name__)

def generate_html_from_markdown(markdown_file, output_html=None, title=None):
    """
    Convert a markdown file back to HTML
    
    Args:
        markdown_file (str): Path to markdown file
        output_html (str, optional): Output HTML file path
        title (str, optional): Page title
        
    Returns:
        str: Generated HTML content
    """
    try:
        # Read markdown file
        with open(markdown_file, 'r', encoding='utf-8') as f:
            md_content = f.read()
        
        # Extract title and source URL from markdown
        lines = md_content.split('\n')
        page_title = title or "Scraped Page"
        source_url = ""
        
        # Parse metadata from markdown
        content_start = 0
        for i, line in enumerate(lines):
            if line.startswith('# '):
                page_title = line[2:].strip()
            elif line.startswith('Source: '):
                source_url = line[8:].strip()
            elif line.strip() == '---':
                content_start = i + 1
                break
        
        # Get actual content (after metadata)
        if content_start > 0:
            md_content = '\n'.join(lines[content_start:])
        
        # Convert markdown to HTML
        html_content = markdown.markdown(
            md_content,
            extensions=[
                'extra',
                'codehilite',
                'tables',
                'fenced_code',
                'nl2br'
            ]
        )
        
        # Create full HTML page
        full_html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{page_title}</title>
    <style>
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
            line-height: 1.6;
            max-width: 1200px;
            margin: 0 auto;
            padding: 20px;
            color: #333;
            background-color: #f5f5f5;
        }}
        .container {{
            background: white;
            padding: 40px;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }}
        .metadata {{
            background: #f8f9fa;
            padding: 15px;
            border-radius: 4px;
            margin-bottom: 30px;
            border-left: 4px solid #007bff;
        }}
        .metadata p {{
            margin: 5px 0;
            font-size: 14px;
            color: #666;
        }}
        .metadata a {{
            color: #007bff;
            text-decoration: none;
        }}
        .metadata a:hover {{
            text-decoration: underline;
        }}
        h1, h2, h3, h4, h5, h6 {{
            color: #2c3e50;
            margin-top: 24px;
            margin-bottom: 16px;
        }}
        h1 {{
            border-bottom: 2px solid #eee;
            padding-bottom: 10px;
        }}
        a {{
            color: #007bff;
            text-decoration: none;
        }}
        a:hover {{
            text-decoration: underline;
        }}
        code {{
            background: #f4f4f4;
            padding: 2px 6px;
            border-radius: 3px;
            font-family: 'Courier New', monospace;
            font-size: 0.9em;
        }}
        pre {{
            background: #f4f4f4;
            padding: 16px;
            border-radius: 4px;
            overflow-x: auto;
        }}
        pre code {{
            background: none;
            padding: 0;
        }}
        table {{
            border-collapse: collapse;
            width: 100%;
            margin: 20px 0;
        }}
        th, td {{
            border: 1px solid #ddd;
            padding: 12px;
            text-align: left;
        }}
        th {{
            background-color: #f8f9fa;
            font-weight: 600;
        }}
        tr:nth-child(even) {{
            background-color: #f9f9f9;
        }}
        img {{
            max-width: 100%;
            height: auto;
            border-radius: 4px;
        }}
        blockquote {{
            border-left: 4px solid #ddd;
            padding-left: 20px;
            margin-left: 0;
            color: #666;
            font-style: italic;
        }}
        ul, ol {{
            padding-left: 30px;
        }}
        li {{
            margin: 8px 0;
        }}
    </style>
</head>
<body>
    <div class="container">
        <div class="metadata">
            <p><strong>Replicated from:</strong> <a href="{source_url}" target="_blank">{source_url}</a></p>
            <p><strong>Generated by:</strong> SiteSlayer Web Scraper</p>
        </div>
        {html_content}
    </div>
</body>
</html>"""
        
        # Save to file if output path provided
        if output_html:
            output_path = Path(output_html)
            output_path.parent.mkdir(parents=True, exist_ok=True)
            
            with open(output_path, 'w', encoding='utf-8') as f:
                f.write(full_html)
            
            logger.info(f"Generated HTML saved to: {output_path}")
        
        return full_html
        
    except Exception as e:
        logger.error(f"Error generating HTML: {str(e)}", exc_info=True)
        return None


def generate_index_page(output_dir, title="Scraped Website"):
    """
    Generate an index page listing all scraped pages
    
    Args:
        output_dir (Path): Directory containing markdown files
        title (str): Index page title
    """
    try:
        md_files = list(Path(output_dir).glob('*.md'))
        
        if not md_files:
            logger.warning("No markdown files found to generate index")
            return
        
        # Create index HTML
        links_html = ""
        for md_file in sorted(md_files):
            html_filename = md_file.stem + '.html'
            page_title = md_file.stem.replace('_', ' ').title()
            
            links_html += f'<li><a href="{html_filename}">{page_title}</a></li>\n'
        
        index_html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title} - Index</title>
    <style>
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
            line-height: 1.6;
            max-width: 1200px;
            margin: 0 auto;
            padding: 20px;
            color: #333;
            background-color: #f5f5f5;
        }}
        .container {{
            background: white;
            padding: 40px;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }}
        h1 {{
            color: #2c3e50;
            border-bottom: 2px solid #eee;
            padding-bottom: 10px;
        }}
        ul {{
            list-style: none;
            padding: 0;
        }}
        li {{
            margin: 15px 0;
            padding: 15px;
            background: #f8f9fa;
            border-radius: 4px;
            transition: background 0.2s;
        }}
        li:hover {{
            background: #e9ecef;
        }}
        a {{
            color: #007bff;
            text-decoration: none;
            font-size: 18px;
        }}
        a:hover {{
            text-decoration: underline;
        }}
        .footer {{
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #eee;
            color: #666;
            font-size: 14px;
        }}
    </style>
</head>
<body>
    <div class="container">
        <h1>{title}</h1>
        <p>Below is a list of all scraped pages from this website:</p>
        <ul>
{links_html}
        </ul>
        <div class="footer">
            <p>Generated by SiteSlayer Web Scraper | Total Pages: {len(md_files)}</p>
        </div>
    </div>
</body>
</html>"""
        
        index_path = Path(output_dir) / 'index.html'
        with open(index_path, 'w', encoding='utf-8') as f:
            f.write(index_html)
        
        logger.info(f"Index page created: {index_path}")
        
    except Exception as e:
        logger.error(f"Error generating index page: {str(e)}", exc_info=True)
